In [6]:
# 資料類型
# 使用 dtype 屬性來指定或檢視
# 可用 int, float, complex, bool, string_ , unicode_
import numpy as np
arr = np.ones(5, dtype = 'int32')
print(arr.dtype)
arr = np.ones(5, dtype = 'float64')
print(arr.dtype)

arr = np.array(["中文", "One", "True"])
print(arr.dtype)

int32
float64
<U4


In [7]:
# ndarray 只能容許一個變數類型
# 同時儲存有數值，布林值，會被自動轉換為數值
# 同時儲存有數值，布林值與文字，會被自動轉換為文字

arr = np.array([100, False, 'True'])      # 給預設值, 自動轉換為文字
print(arr.dtype)
print(arr)

<U11
['100' 'False' 'True']


In [10]:
# 用索引值可以可以跳著選值
arr = np.arange(10, 20)
print(arr[[0, 4, 6]])

[10 14 16]


In [9]:
# list 無法跳著選值
lst = list(range(10, 20))
print(lst[0, 4, 6])

TypeError: list indices must be integers or slices, not tuple

In [11]:
arr = np.arange(10, 20)
print(arr[:5])
print(arr[5:])
print(arr[0:10:3])
# 實務上是用條件選元素

[10 11 12 13 14]
[15 16 17 18 19]
[10 13 16 19]


In [13]:
arr = np.arange(10, 20)
print(arr > 15)            # 用條件式判斷後回傳
print(arr[arr > 15])

[False False False False False False  True  True  True  True]
[16 17 18 19]


In [14]:
arr = np.array([
    [1, 3, 5], 
    [2, 4, 6]
])
print(arr[1, 2])     # 第一個 row, 第二個 column值
print(arr[:, 1])     # 全部 row的第一個 column值 

6
[3 4]


In [19]:
arr = np.arange(20).reshape(2, 5, 2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [32]:
# 練習 1
# 選出未滿 20 與超過 30 的元素

age = np.array([19, 21, 20, 19, 21, 17, 30, 36, 90])     # 記得要轉換成 array
# print((age < 20) | (age > 30))
age_filter = (age < 20) | (age > 30)
print(age[age_filter])
age_filter = np.logical_or(age < 20, age > 30)           # 適用 array 的 logical_or
print(age[age_filter])

[19 19 17 36 90]
[19 19 17 36 90]


In [33]:
# 練習 2
# 從五人中選出 BMI > 21 的元素

heights = np.array([173, 168, 171, 189, 179])
weights = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmis = weights / (heights/100)**2
print(bmis[bmis > 21])

[ 21.85171573  21.75028214  24.7473475   21.44127836]


In [39]:
# 練習 3
# 使用布林選出 Matthew Perry 與 Lisa Kudrow

friends_stars = np.array(["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow",
"Matt LeBlanc", "Matthew Perry", "David Schwimmer"])

charcter_filter = np.logical_or(friends_stars == "Lisa Kudrow", friends_stars == "Matthew Perry")
print(friends_stars[charcter_filter])

charcter_filter = np.in1d(friends_stars, ["Lisa Kudrow", "Matthew Perry"])
print(friends_stars[charcter_filter])

['Lisa Kudrow' 'Matthew Perry']
['Lisa Kudrow' 'Matthew Perry']
