In [1]:
import numpy as np

# 二維矩陣運算
arr_1 = np.arange(10).reshape(2, 5)
arr_2 = np.arange(10).reshape(2, 5)
# 2*5 矩陣無法乘上內積

print(arr_1 * arr_2)

[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [2]:
import numpy as np

# 二維的 ndarray 可以進行矩陣的內積運算
# 使用 .dot() 方法或 np.dot()
arr_1 = np.arange(4).reshape(2, 2)
arr_2 = np.arange(4).reshape(2, 2)
print(arr_1 * arr_2)
print(np.dot(arr_1, arr_2))   # 可使用 dot作矩陣乘績

[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]


In [41]:
# 練習 1
u = np.array([4, -4, -3]).reshape(3, 1)
v = np.array([4, 2, 4]).reshape(3, 1)

print(np.dot(u.transpose(), v))
# 另一種乘積方式
print(u.T.dot(v))

[[-4]]
[[-4]]


In [7]:
# 練習 1, 老師解法

u_T = np.array([
    [4, -4, -3]
])
v = np.array([
    [4],
    [2],
    [4]
])

# 轉置函數
print(np.dot(u_T, v))

[[-4]]


In [11]:
# 練習 2

A = np.arange(1, 10).reshape(3, 3)
I = np.eye(3)
print(np.dot(A, I))
print(np.dot(I, A))   # 順序交換不影響結果

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [13]:
# 練習 3

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
I = np.eye(3)

print(np.dot(A, I))
print(np.dot(I, A))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [12]:
# 練習 4

import numpy as np

A = np.array([
    [1, 2],
    [4, 5]
])
B = np.array([
    [4, 3],
    [2, 1]
])

print(np.dot(A, B))
print(np.dot(B, A))

[[ 8  5]
 [26 17]]
[[16 23]
 [ 6  9]]


In [17]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [4, 3],
    [2, 1]
])

# 元素個數：.size
# 外觀：.shape
# 維度：.ndim
print(A.size)
print(A.shape)   # 回傳 tuple
print(A.ndim)

6
(2, 3)
2


In [24]:
# 變形：.reshape(m, n)
# 轉置：.T
# 攤平：.ravel()
# 依條件取代：.where()

A = np.arange(16).reshape(2, 2, 4)   # 
B = np.array([
    [4, 3],
    [2, 1]
])

u = np.array([
    [4],
    [-4],
    [3]
])

u_T = u.T
A = A.ravel()
print(u_T)
print(A.ravel())
print(np.where(A < 8, 999, A))

[[ 4 -4  3]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[999 999 999 999 999 999 999 999   8   9  10  11  12  13  14  15]


In [26]:
import numpy as np

A = np.arange(16).reshape(4, 4)
print(A)
print("\n")
print(np.sum(A, axis = 0))    # 做 column 的加總
print("\n")
print(np.sum(A, axis = 1))    # 做 row 的加總

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[24 28 32 36]


[ 6 22 38 54]


In [32]:
# 練習 5
# 建立一個外觀為 (9, 9) 的 ndarray
# 填入九九乘法表

A = np.arange(1, 10).reshape(1, 9)
# B = A.T
# print(A)
# print(B)
print(A.T * A)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [33]:
# 練習 5, 老師解法
# 建立一個外觀為 (9, 9) 的 ndarray
# 填入九九乘法表

arr_1 = np.arange(1,10).reshape(9, 1)
arr_2 = np.arange(1,10).reshape(1, 9)
print(np.dot(arr_1, arr_2))

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [42]:
import numpy as np

arr_1 = np.arange(1, 10).reshape(9, 1)
arr_2 = np.arange(1, 10).reshape(1, 9)
print(np.dot(arr_1, arr_2))

print("======")

mat = np.zeros(81).reshape(9, 9)
mat = mat.astype('str')
nrow, ncol = mat.shape

for i in range(nrow):
    for j in range(ncol):
        mat[i, j] = str(i+1) + "x" + str(j+1) + "=" + str((i+1)*(j+1))

print(mat)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[['1x1=1' '1x2=2' '1x3=3' '1x4=4' '1x5=5' '1x6=6' '1x7=7' '1x8=8' '1x9=9']
 ['2x1=2' '2x2=4' '2x3=6' '2x4=8' '2x5=10' '2x6=12' '2x7=14' '2x8=16'
  '2x9=18']
 ['3x1=3' '3x2=6' '3x3=9' '3x4=12' '3x5=15' '3x6=18' '3x7=21' '3x8=24'
  '3x9=27']
 ['4x1=4' '4x2=8' '4x3=12' '4x4=16' '4x5=20' '4x6=24' '4x7=28' '4x8=32'
  '4x9=36']
 ['5x1=5' '5x2=10' '5x3=15' '5x4=20' '5x5=25' '5x6=30' '5x7=35' '5x8=40'
  '5x9=45']
 ['6x1=6' '6x2=12' '6x3=18' '6x4=24' '6x5=30' '6x6=36' '6x7=42' '6x8=48'
  '6x9=54']
 ['7x1=7' '7x2=14' '7x3=21' '7x4=28' '7x5=35' '7x6=42' '7x7=49' '7x8=56'
  '7x9=63']
 ['8x1=8' '8x2=16' '8x3=24' '8x4=32' '8x5=40' '8x6=48' '8x7=56' '8x8=64'
  '8x9=72']
 ['9x1=9' '9x2=18' '9x3=27' '9x4=36' '9x5=45' '9x6=54' '9x7=63' '